<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-OnlineCoursesPlatform-bb6b7e0c-404d-40f2-8992-5189c309941d</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Areas\Identity\Data\OnlineCoursesPlatformIdentityDbContext.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="Areas\Admin\Views\Content\Index.cshtml" />
	  <Content Remove="Views\Shared\_RegisterPartial.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />

		<!-- EF Core design-time tools -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- EF Core provider -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />

		<!-- EF Core CLI tools (for migrations) -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- Scaffolding packages -->
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="9.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Admin\Controllers\" />
		<Folder Include="Areas\Admin\Data\" />
		<Folder Include="Areas\Admin\Models\" />
		<Folder Include="Areas\Identity\Data\" />
	</ItemGroup>

</Project>
